/*
 * FRANK NES - NES Emulator for RP2350
 * Copyright (c) 2026 Mikhail Matveev <xtreme@rh1.tech>
 * https://rh1.tech | https://github.com/rh1tech/frank-nes
 * SPDX-License-Identifier: MIT
 */

#ifndef QUICKNES_H
#define QUICKNES_H

#include <stdint.h>

#define QNES_REGION_NTSC  0
#define QNES_REGION_DENDY 1

#ifdef __cplusplus
extern "C" {
#endif

/* Set emulation region (NTSC or Dendy). Must be called BEFORE qnes_load_rom.
 * Default is NTSC. */
void qnes_set_region(int region);

/* Get current region. */
int qnes_get_region(void);

/* Enable or disable the NES 8-sprites-per-scanline limit.
 * enabled=1 (default): hardware-accurate limit — sprites beyond 8 per scanline
 * flicker as on real hardware. enabled=0: render all sprites (no flicker). */
void qnes_set_sprite_limit(int enabled);

/* Audio equalizer presets — tonal color of the APU mix. Does not affect
 * emulation accuracy. Valid values: 0..QNES_EQ_COUNT-1. Default QNES_EQ_NES. */
#define QNES_EQ_NES     0  /* NES (default) */
#define QNES_EQ_FAMICOM 1  /* Famicom */
#define QNES_EQ_TV      2  /* muffled TV speaker */
#define QNES_EQ_FLAT    3  /* flat — no coloring */
#define QNES_EQ_CRISP   4  /* treble boost */
#define QNES_EQ_TINNY   5  /* handheld-speaker sound */
#define QNES_EQ_COUNT   6
void qnes_set_audio_eq(int preset);

/* Disable the background layer (debug/practice aid). Sprites and CPU
 * timing are unaffected. */
void qnes_set_bg_disabled(int disabled);

/* Per-2A03-oscillator mute mask. Bits:
 *   0 = pulse 1
 *   1 = pulse 2
 *   2 = triangle
 *   3 = noise
 *   4 = DMC
 * Pass any combination. 0 = un-mute all. */
#define QNES_CHAN_PULSE1   (1u << 0)
#define QNES_CHAN_PULSE2   (1u << 1)
#define QNES_CHAN_TRIANGLE (1u << 2)
#define QNES_CHAN_NOISE    (1u << 3)
#define QNES_CHAN_DMC      (1u << 4)
void qnes_set_channel_mute_mask(unsigned mask);

/* Apply a 6- or 8-character Game Genie code to the currently loaded ROM.
 * Code is patched into the cart PRG in place, so it survives qnes_reset
 * but is lost on the next qnes_load_rom call. Returns 0 on success and
 * non-zero if the code is malformed or doesn't match any bank. */
int qnes_apply_game_genie(const char *code);

/* Mute/unmute the mapper expansion-audio channels (VRC6, VRC7, MMC5,
 * Namco 163, FME-7, ...). 2A03 channels are unaffected. */
void qnes_set_expansion_muted(int muted);

/* Additional low-pass roll-off on top of the current audio EQ preset.
 * 0 = no change, increasing values lower the treble cutoff. Max is
 * QNES_LOWPASS_MAX; mapping is linear in dB, ending at roughly -20 dB. */
#define QNES_LOWPASS_MAX 10
void qnes_set_lowpass(int amount);

/* Initialize emulator. Call once at startup.
 * Returns 0 on success, non-zero on error. */
int qnes_init(long sample_rate);

/* Load iNES ROM from memory buffer (copies PRG/CHR internally).
 * Returns 0 on success, non-zero on error. */
int qnes_load_rom(const void *data, long size);

/* Load iNES ROM from memory buffer. PRG is copied to SRAM for fast CPU
 * access; CHR remains a direct reference into the buffer (must stay valid).
 * Returns 0 on success, non-zero on error. */
int qnes_load_rom_inplace(const void *data, long size);

/* Emulate one frame.
 * joypad1/joypad2: button bitmask (A=0, B=1, Sel=2, Start=3, U=4, D=5, L=6, R=7)
 * Returns 0 on success. */
int qnes_emulate_frame(int joypad1, int joypad2);

/* Get pointer to indexed pixel buffer after emulate_frame().
 * Returns 256x240 array of 8-bit palette indices.
 * pitch: bytes per row (set by caller via qnes_set_pixels). */
const uint8_t *qnes_get_pixels(void);

/* Number of visible sprites (Y < 0xF0) in OAM after last frame.
 * Used to detect 30 Hz sprite blink patterns. */
int qnes_get_visible_sprite_count(void);

/* Get the current frame's palette.
 * Each entry is a NES color index (0-511) into the color table.
 * out_size: number of palette entries this frame.
 * Returns pointer to palette array (up to 256 entries). */
const int16_t *qnes_get_palette(int *out_size);

/* NES master color table: 512 entries (64 base colors x 8 emphasis modes).
 * Each entry: r, g, b bytes. */
typedef struct { uint8_t r, g, b; } qnes_rgb_t;
const qnes_rgb_t *qnes_get_color_table(void);

/* Read audio samples generated by last frame.
 * out: buffer for 16-bit signed mono samples.
 * max_samples: buffer capacity.
 * Returns number of samples written. */
long qnes_read_samples(int16_t *out, long max_samples);

/* Provide a PSRAM buffer for the PPU tile cache (large CHR games).
 * Must be called before qnes_load_rom*. NULL to use heap (default). */
void qnes_set_tile_cache_buf(void *buf, long size);

/* Opaque file handle for save state I/O (cast to FIL* from ff.h) */
typedef void *qnes_file_t;

/* Save emulator state directly to an open file.
 * Returns 0 on success, non-zero on error. */
int qnes_save_state(qnes_file_t file);

/* Load emulator state directly from an open file.
 * file_size: total bytes in the file.
 * Returns 0 on success, non-zero on error. */
int qnes_load_state(qnes_file_t file, long file_size);

/* Reset emulator. full_reset=1 for power cycle, 0 for reset button. */
void qnes_reset(int full_reset);

/* Shut down emulator and free resources. */
void qnes_close(void);

#ifdef __cplusplus
}
#endif

#endif /* QUICKNES_H */
